- hosts: localhost
  tasks:
  - name: Copy alacritty.toml
    copy:
      src: files/alacritty.toml
      dest: /home/{{ ansible_user_id }}/.config/alacritty/alacritty.toml
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: '0664'
