- hosts: localhost
  tasks:
  - name: Download Android Studio
    get_url:
      url: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2024.1.1.12/android-studio-2024.1.1.12-linux.tar.gz
      dest: /tmp/android-studio.tar.gz

  - name: Create unpack dir for Android Studio
    file:
      path: /home/{{ ansible_user_id }}/android-studio
      state: directory

  - name: Unpack Android Studio
    unarchive:
      src: /tmp/android-studio.tar.gz
      dest: /home/{{ ansible_user_id }}/android-studio
      remote_src: yes

  - name: Create Android Studio desktop file
    template:
      src: files/android-studio.desktop.j2
      dest: /home/{{ ansible_user_id }}/.local/share/applications/jetbrains-studio.desktop
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: '0600'
