- hosts: localhost
  tasks:
  - name: Configure GCM
    command: git-credential-manager configure

  - name: Configure GCM for Secret Service
    command: git config --global credential.credentialStore secretservice

  - name: Download git-profile-manager
    get_url:
      url: https://github.com/dm3ch/git-profile-manager/releases/download/v2.0.3/git-profile-manager_2.0.3_Linux_x86_64.tar.gz
      dest: /tmp/git-profile-manager.tar.gz

  - name: Create unpack dir for git-profile-manager
    file:
      path: /tmp/git-profile-manager
      state: directory

  - name: Unpack git-profile-manager
    unarchive:
      src: /tmp/git-profile-manager.tar.gz
      dest: /tmp/git-profile-manager
      remote_src: yes

  - name: Install git-profile-manager
    copy:
      src: /tmp/git-profile-manager/git-profile-manager
      dest: /home/{{ ansible_user_id }}/.local/bin/git-profile-manager
      mode: '0755'

  - name: Print message
    debug:
      msg: "Please run 'git-profile-manager add' to add new git profiles"
