- hosts: localhost
  tasks:
    - name: Install Firefox (deb over snap)
      tags: firefox
      include_tasks: tasks/firefox.yml

    - name: Install git, GCM and git-profile-manager
      tags: git
      include_tasks: tasks/git.yml

    - name: Install fonts
      tags: fonts
      include_tasks: tasks/fonts.yml

    - name: Install zsh
      tags: zsh
      include_tasks: tasks/zsh.yml

    - name: Install Docker
      tags: docker
      include_tasks: tasks/docker.yml
    
    - name: Install Alacritty
      tags: alacritty
      include_tasks: tasks/alacritty.yml

    - name: Install Android Studio
      tags: android-studio
      include_tasks: tasks/android-studio.yml
    
    - name: Configure Gnome
      tags: gnome
      include_tasks: tasks/gnome.yml

# todo: rust, python (uv), nodejs, flyctl