- hosts: localhost
  tasks:
  - name: Install apt prerequisites
    become: yes
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present

  - name: Add Docker GPG key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repository
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

  - name: Add Syncthing PGP keys:
    become: yes
    apt_key:
      url: https://syncthing.net/release-key.gpg
      state: present

  - name: Add Syncthing repository
    become: yes
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
      state: present

  - name: Add Tailscale GPG key
    become: yes
    apt_key:
      url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
      state: present

  - name: Add Tailscale repository
    become: yes
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
      state: present

  - name: Add system76 PPA
    become: yes
    apt_repository:
      repo: "ppa:system76-dev/stable"
      state: present

  - name: Install applications
    become: yes
    apt:
      pkg:
        - alacritty
        - containerd.io
        - docker-buildx-plugin
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - fcitx5
        - fcitx5-chinese-addons
        - git
        - ibus-pinyin
        - lutris
        - p7zip-full
        - p7zip-rar
        - steam
        - syncthing
        - system76-driver
        - tailscale
        - unrar
        - unzip
        - zsh
      state: present
  
  - name: Download GCM
    get_url:
      url: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.5.1/gcm-linux_amd64.2.5.1.deb
      dest: /tmp/gcm.deb

  - name: Install GCM
    become: yes
    apt:
      deb: /tmp/gcm.deb
      state: present

  - name: Download VSCode
    get_url:
      url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      dest: /tmp/vscode.deb

  - name: Install VSCode
    become: yes
    apt:
      deb: /tmp/vscode.deb
      state: present

  - name: Download 1Password
    get_url:
      url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
      dest: /tmp/1password.deb

  - name: Install 1Password
    become: yes
    apt:
      deb: /tmp/1password.deb
      state: present

  - name: Download LocalSend
    get_url:
      url: https://github.com/localsend/localsend/releases/download/v1.17.0/LocalSend-1.17.0-linux-x86-64.deb
      dest: /tmp/localsend.deb

  - name: Install LocalSend
    become: yes
    apt:
      deb: /tmp/localsend.deb
      state: present

  - name: Remove Firefox snap version
    become: yes
    community.general.snap:
      name: firefox
      state: absent

  - name: Add Firefox GPG key
    become: yes
    apt_key:
      url: https://packages.mozilla.org/apt/repo-signing-key.gpg
      state: present

  - name: Add Firefox repository
    become: yes
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main"
      state: present

  - name: Pin firefox package debian over snap
    become: yes
    copy:
      src: files/firefox-pin
      dest: /etc/apt/preferences.d/mozilla
      owner: root
      group: root
      mode: '0644'

  - name: Install Firefox
    become: yes
    apt:
      pkg:
        - firefox
      state: present
