- name: Install prerequisites
  become: yes
  apt:
    pkg:
      - zsh
      - curl
      - git
    state: present

- name: Change default shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh  # todo: hardcoded?

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: /home/{{ ansible_user_id }}/.oh-my-zsh

- name: Install zsh-completions
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/zsh-completions
    update: no

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: no

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    update: no

- name: Copy .zshrc
  copy:
    src: files/zshrc
    dest: /home/{{ ansible_user_id }}/.zshrc
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'