export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
plugins=(
    git
    zsh-completions
    zsh-autosuggestions
    zsh-syntax-highlighting
)
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
source $ZSH/oh-my-zsh.sh

export PATH=$HOME/.local/bin:$PATH
source <(git-profile-manager completion zsh)

export FLYCTL_INSTALL="$HOME/.fly"
export PATH=$FLYCTL_INSTALL/bin:$PATH
export PATH=/usr/local/go/bin:$PATH

download-yt-audio() {
    if [ -z "$1" ]; then
        echo "Usage: download-yt-audio <YouTube URL>"
        return 1
    fi
    yt-dlp -f bestaudio -x --audio-format mp3 --audio-quality 0 "$1"
}

alias vs="vscli open"
alias vsr="vscli recent"
